apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl-serviceaccount
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-list-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: curl-serviceaccount
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
spec:
  serviceAccountName: curl-serviceaccount
  containers:
  - name: curl-container
    image: curlimages/curl
    command: ["sleep", "infinity"]